### ISSUE TITLE
createflaskapp.config does not exists.

### ISSUE THREAD

**Issue by husudosu** [Gl0deanR/create-flask-app#1]
Hi! 
I'm 'husudosu' from Reddit r/flask. After cloning your project I tried to start the migration procedure  but  config.py file missing by default. I'd suggest using creating config.py by default on the package and maybe use a class-based Config. 

I imagine something like this:

```python
# This is config.py

# In my opinion better practice to use .env files instead requiring users/developers to edit .py files before starting out with a project.
# you could load environment file based on FLASK_DEBUG environment variable. If FLASK_DEBUG not present on the system, it means we running on production config.
# dotenv is a 3rd party lib https://pypi.org/project/python-dotenv/
from dotenv import load_dotenv

if os.environ.get("FLASK_DEBUG") == 1:
    load_dotenv("development.env")
else:
    load_dotenv("production.env")

class Config:
    SQLALCHEMY_DATABASE_URI = os.environ.get("SQLALCHEMY_DATABASE_URI")
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = os.environ.get("SECRET_KEY")
    # Other options...
```

```python
# createflaskapp.__init__.py
# You import Config class and 

app.config.from_object(Config)

# And you don't need to set SECRET_KEY, DATABASE URI or other options on your __init__.py.
```

Note: This implementation only a draft, so this is not the full code. I'm using pattern like this on my production projects.

**Comment by Gl0deanR** [comment]
Hey, thanks for pointing this out.
I thought about it before posting on Reddit but forgot to remove it. It's clear that you should only use some config file or the environmental files. I currently removed the necessity of the config file with the latest commit so it works on the go.
Please do another pull now and let me know.
